// Generated by gencpp from file monitor_utils/node_watchdog_service.msg
// DO NOT EDIT!


#ifndef MONITOR_UTILS_MESSAGE_NODE_WATCHDOG_SERVICE_H
#define MONITOR_UTILS_MESSAGE_NODE_WATCHDOG_SERVICE_H

#include <ros/service_traits.h>


#include <monitor_utils/node_watchdog_serviceRequest.h>
#include <monitor_utils/node_watchdog_serviceResponse.h>


namespace monitor_utils
{

struct node_watchdog_service
{

typedef node_watchdog_serviceRequest Request;
typedef node_watchdog_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_watchdog_service
} // namespace monitor_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::monitor_utils::node_watchdog_service > {
  static const char* value()
  {
    return "966c5e764adcdb27f4f871b3066bf913";
  }

  static const char* value(const ::monitor_utils::node_watchdog_service&) { return value(); }
};

template<>
struct DataType< ::monitor_utils::node_watchdog_service > {
  static const char* value()
  {
    return "monitor_utils/node_watchdog_service";
  }

  static const char* value(const ::monitor_utils::node_watchdog_service&) { return value(); }
};


// service_traits::MD5Sum< ::monitor_utils::node_watchdog_serviceRequest> should match
// service_traits::MD5Sum< ::monitor_utils::node_watchdog_service >
template<>
struct MD5Sum< ::monitor_utils::node_watchdog_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::monitor_utils::node_watchdog_service >::value();
  }
  static const char* value(const ::monitor_utils::node_watchdog_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::monitor_utils::node_watchdog_serviceRequest> should match
// service_traits::DataType< ::monitor_utils::node_watchdog_service >
template<>
struct DataType< ::monitor_utils::node_watchdog_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::monitor_utils::node_watchdog_service >::value();
  }
  static const char* value(const ::monitor_utils::node_watchdog_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::monitor_utils::node_watchdog_serviceResponse> should match
// service_traits::MD5Sum< ::monitor_utils::node_watchdog_service >
template<>
struct MD5Sum< ::monitor_utils::node_watchdog_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::monitor_utils::node_watchdog_service >::value();
  }
  static const char* value(const ::monitor_utils::node_watchdog_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::monitor_utils::node_watchdog_serviceResponse> should match
// service_traits::DataType< ::monitor_utils::node_watchdog_service >
template<>
struct DataType< ::monitor_utils::node_watchdog_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::monitor_utils::node_watchdog_service >::value();
  }
  static const char* value(const ::monitor_utils::node_watchdog_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MONITOR_UTILS_MESSAGE_NODE_WATCHDOG_SERVICE_H
