; Auto-generated. Do not edit!


(cl:in-package fuse_navigation_msgs-msg)


;//! \htmlinclude ExecutePathResult.msg.html

(cl:defclass <ExecutePathResult> (roslisp-msg-protocol:ros-message)
  ((finished_mission
    :reader finished_mission
    :initarg :finished_mission
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ExecutePathResult (<ExecutePathResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecutePathResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecutePathResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fuse_navigation_msgs-msg:<ExecutePathResult> is deprecated: use fuse_navigation_msgs-msg:ExecutePathResult instead.")))

(cl:ensure-generic-function 'finished_mission-val :lambda-list '(m))
(cl:defmethod finished_mission-val ((m <ExecutePathResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fuse_navigation_msgs-msg:finished_mission-val is deprecated.  Use fuse_navigation_msgs-msg:finished_mission instead.")
  (finished_mission m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecutePathResult>) ostream)
  "Serializes a message object of type '<ExecutePathResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finished_mission) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecutePathResult>) istream)
  "Deserializes a message object of type '<ExecutePathResult>"
    (cl:setf (cl:slot-value msg 'finished_mission) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecutePathResult>)))
  "Returns string type for a message object of type '<ExecutePathResult>"
  "fuse_navigation_msgs/ExecutePathResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecutePathResult)))
  "Returns string type for a message object of type 'ExecutePathResult"
  "fuse_navigation_msgs/ExecutePathResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecutePathResult>)))
  "Returns md5sum for a message object of type '<ExecutePathResult>"
  "d54e29b77f6150086a487e84800793cc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecutePathResult)))
  "Returns md5sum for a message object of type 'ExecutePathResult"
  "d54e29b77f6150086a487e84800793cc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecutePathResult>)))
  "Returns full string definition for message of type '<ExecutePathResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool finished_mission~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecutePathResult)))
  "Returns full string definition for message of type 'ExecutePathResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool finished_mission~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecutePathResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecutePathResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecutePathResult
    (cl:cons ':finished_mission (finished_mission msg))
))
