// Generated by gencpp from file fuse_navigation_msgs/TaskAction.msg
// DO NOT EDIT!


#ifndef FUSE_NAVIGATION_MSGS_MESSAGE_TASKACTION_H
#define FUSE_NAVIGATION_MSGS_MESSAGE_TASKACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fuse_navigation_msgs
{
template <class ContainerAllocator>
struct TaskAction_
{
  typedef TaskAction_<ContainerAllocator> Type;

  TaskAction_()
    : name()
    , arguments()  {
    }
  TaskAction_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , arguments(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _arguments_type;
  _arguments_type arguments;





  typedef boost::shared_ptr< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> const> ConstPtr;

}; // struct TaskAction_

typedef ::fuse_navigation_msgs::TaskAction_<std::allocator<void> > TaskAction;

typedef boost::shared_ptr< ::fuse_navigation_msgs::TaskAction > TaskActionPtr;
typedef boost::shared_ptr< ::fuse_navigation_msgs::TaskAction const> TaskActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fuse_navigation_msgs::TaskAction_<ContainerAllocator1> & lhs, const ::fuse_navigation_msgs::TaskAction_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.arguments == rhs.arguments;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fuse_navigation_msgs::TaskAction_<ContainerAllocator1> & lhs, const ::fuse_navigation_msgs::TaskAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fuse_navigation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c435bb0ff50e10a641eea4b6379dd80a";
  }

  static const char* value(const ::fuse_navigation_msgs::TaskAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc435bb0ff50e10a6ULL;
  static const uint64_t static_value2 = 0x41eea4b6379dd80aULL;
};

template<class ContainerAllocator>
struct DataType< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fuse_navigation_msgs/TaskAction";
  }

  static const char* value(const ::fuse_navigation_msgs::TaskAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents an action as part of a larger agent task\n"
"string name\n"
"string[] arguments\n"
;
  }

  static const char* value(const ::fuse_navigation_msgs::TaskAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.arguments);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fuse_navigation_msgs::TaskAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fuse_navigation_msgs::TaskAction_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "arguments[]" << std::endl;
    for (size_t i = 0; i < v.arguments.size(); ++i)
    {
      s << indent << "  arguments[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.arguments[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUSE_NAVIGATION_MSGS_MESSAGE_TASKACTION_H
