// Generated by gencpp from file accerion_driver_msgs/ImportG2oGoal.msg
// DO NOT EDIT!


#ifndef ACCERION_DRIVER_MSGS_MESSAGE_IMPORTG2OGOAL_H
#define ACCERION_DRIVER_MSGS_MESSAGE_IMPORTG2OGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace accerion_driver_msgs
{
template <class ContainerAllocator>
struct ImportG2oGoal_
{
  typedef ImportG2oGoal_<ContainerAllocator> Type;

  ImportG2oGoal_()
    {
    }
  ImportG2oGoal_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ImportG2oGoal_

typedef ::accerion_driver_msgs::ImportG2oGoal_<std::allocator<void> > ImportG2oGoal;

typedef boost::shared_ptr< ::accerion_driver_msgs::ImportG2oGoal > ImportG2oGoalPtr;
typedef boost::shared_ptr< ::accerion_driver_msgs::ImportG2oGoal const> ImportG2oGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace accerion_driver_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "accerion_driver_msgs/ImportG2oGoal";
  }

  static const char* value(const ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
;
  }

  static const char* value(const ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImportG2oGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::accerion_driver_msgs::ImportG2oGoal_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ACCERION_DRIVER_MSGS_MESSAGE_IMPORTG2OGOAL_H
