// Generated by gencpp from file accerion_driver_msgs/RequestCommandRequest.msg
// DO NOT EDIT!


#ifndef ACCERION_DRIVER_MSGS_MESSAGE_REQUESTCOMMANDREQUEST_H
#define ACCERION_DRIVER_MSGS_MESSAGE_REQUESTCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace accerion_driver_msgs
{
template <class ContainerAllocator>
struct RequestCommandRequest_
{
  typedef RequestCommandRequest_<ContainerAllocator> Type;

  RequestCommandRequest_()
    : request_command()  {
    }
  RequestCommandRequest_(const ContainerAllocator& _alloc)
    : request_command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _request_command_type;
  _request_command_type request_command;





  typedef boost::shared_ptr< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RequestCommandRequest_

typedef ::accerion_driver_msgs::RequestCommandRequest_<std::allocator<void> > RequestCommandRequest;

typedef boost::shared_ptr< ::accerion_driver_msgs::RequestCommandRequest > RequestCommandRequestPtr;
typedef boost::shared_ptr< ::accerion_driver_msgs::RequestCommandRequest const> RequestCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator1> & lhs, const ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request_command == rhs.request_command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator1> & lhs, const ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace accerion_driver_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbe0969e4c43c02ed1ead69cf3f629f5";
  }

  static const char* value(const ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbe0969e4c43c02eULL;
  static const uint64_t static_value2 = 0xd1ead69cf3f629f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "accerion_driver_msgs/RequestCommandRequest";
  }

  static const char* value(const ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request_command      # [map, etc] the desired info\n"
;
  }

  static const char* value(const ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::accerion_driver_msgs::RequestCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.request_command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACCERION_DRIVER_MSGS_MESSAGE_REQUESTCOMMANDREQUEST_H
