// Generated by gencpp from file accerion_driver_msgs/SecondaryLFRequest.msg
// DO NOT EDIT!


#ifndef ACCERION_DRIVER_MSGS_MESSAGE_SECONDARYLFREQUEST_H
#define ACCERION_DRIVER_MSGS_MESSAGE_SECONDARYLFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace accerion_driver_msgs
{
template <class ContainerAllocator>
struct SecondaryLFRequest_
{
  typedef SecondaryLFRequest_<ContainerAllocator> Type;

  SecondaryLFRequest_()
    : clusterID(0)  {
    }
  SecondaryLFRequest_(const ContainerAllocator& _alloc)
    : clusterID(0)  {
  (void)_alloc;
    }



   typedef uint16_t _clusterID_type;
  _clusterID_type clusterID;





  typedef boost::shared_ptr< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SecondaryLFRequest_

typedef ::accerion_driver_msgs::SecondaryLFRequest_<std::allocator<void> > SecondaryLFRequest;

typedef boost::shared_ptr< ::accerion_driver_msgs::SecondaryLFRequest > SecondaryLFRequestPtr;
typedef boost::shared_ptr< ::accerion_driver_msgs::SecondaryLFRequest const> SecondaryLFRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator1> & lhs, const ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator2> & rhs)
{
  return lhs.clusterID == rhs.clusterID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator1> & lhs, const ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace accerion_driver_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0a9a4b847ac5299245224ada02c00e0";
  }

  static const char* value(const ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0a9a4b847ac5299ULL;
  static const uint64_t static_value2 = 0x245224ada02c00e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "accerion_driver_msgs/SecondaryLFRequest";
  }

  static const char* value(const ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 clusterID	      # uint16_t ID of the Cluster that you want the closest point of\n"
;
  }

  static const char* value(const ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clusterID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SecondaryLFRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::accerion_driver_msgs::SecondaryLFRequest_<ContainerAllocator>& v)
  {
    s << indent << "clusterID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.clusterID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACCERION_DRIVER_MSGS_MESSAGE_SECONDARYLFREQUEST_H
