// Generated by gencpp from file accerion_driver_msgs/SetAreaResponse.msg
// DO NOT EDIT!


#ifndef ACCERION_DRIVER_MSGS_MESSAGE_SETAREARESPONSE_H
#define ACCERION_DRIVER_MSGS_MESSAGE_SETAREARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace accerion_driver_msgs
{
template <class ContainerAllocator>
struct SetAreaResponse_
{
  typedef SetAreaResponse_<ContainerAllocator> Type;

  SetAreaResponse_()
    : success(false)
    , activeArea(0)
    , availbleAreas()
    , message()  {
    }
  SetAreaResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , activeArea(0)
    , availbleAreas(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint16_t _activeArea_type;
  _activeArea_type activeArea;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _availbleAreas_type;
  _availbleAreas_type availbleAreas;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetAreaResponse_

typedef ::accerion_driver_msgs::SetAreaResponse_<std::allocator<void> > SetAreaResponse;

typedef boost::shared_ptr< ::accerion_driver_msgs::SetAreaResponse > SetAreaResponsePtr;
typedef boost::shared_ptr< ::accerion_driver_msgs::SetAreaResponse const> SetAreaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator1> & lhs, const ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.activeArea == rhs.activeArea &&
    lhs.availbleAreas == rhs.availbleAreas &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator1> & lhs, const ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace accerion_driver_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c78e2d446f78752232f22114cb77d34e";
  }

  static const char* value(const ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc78e2d446f787522ULL;
  static const uint64_t static_value2 = 0x32f22114cb77d34eULL;
};

template<class ContainerAllocator>
struct DataType< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "accerion_driver_msgs/SetAreaResponse";
  }

  static const char* value(const ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success                    # was the request succesful\n"
"uint16 activeArea   		    # contains the ID of the area that is currently selected\n"
"uint16[]  availbleAreas         # contains the ID's of all the existing areas, the first one being the active one\n"
"string message 				    # informational, e.g. for error messages\n"
;
  }

  static const char* value(const ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.activeArea);
      stream.next(m.availbleAreas);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAreaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::accerion_driver_msgs::SetAreaResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "activeArea: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.activeArea);
    s << indent << "availbleAreas[]" << std::endl;
    for (size_t i = 0; i < v.availbleAreas.size(); ++i)
    {
      s << indent << "  availbleAreas[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.availbleAreas[i]);
    }
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACCERION_DRIVER_MSGS_MESSAGE_SETAREARESPONSE_H
