(cl:defpackage fuse_pathfollowing_msgs-msg
  (:use )
  (:export
   "<DEBUGMETRICS>"
   "DEBUGMETRICS"
   "<PIDMETRICS>"
   "PIDMETRICS"
   "<PATH>"
   "PATH"
   "<SEGMENT>"
   "SEGMENT"
   "<UPDATEPATHACTION>"
   "UPDATEPATHACTION"
   "<UPDATEPATHACTIONFEEDBACK>"
   "UPDATEPATHACTIONFEEDBACK"
   "<UPDATEPATHACTIONGOAL>"
   "UPDATEPATHACTIONGOAL"
   "<UPDATEPATHACTIONRESULT>"
   "UPDATEPATHACTIONRESULT"
   "<UPDATEPATHFEEDBACK>"
   "UPDATEPATHFEEDBACK"
   "<UPDATEPATHGOAL>"
   "UPDATEPATHGOAL"
   "<UPDATEPATHRESULT>"
   "UPDATEPATHRESULT"
  ))

