// Auto-generated. Do not edit!

// (in-package rt_mission_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class mobile_robot_pick_and_placeFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.feedback = null;
      this.percentage_finished = null;
    }
    else {
      if (initObj.hasOwnProperty('feedback')) {
        this.feedback = initObj.feedback
      }
      else {
        this.feedback = '';
      }
      if (initObj.hasOwnProperty('percentage_finished')) {
        this.percentage_finished = initObj.percentage_finished
      }
      else {
        this.percentage_finished = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type mobile_robot_pick_and_placeFeedback
    // Serialize message field [feedback]
    bufferOffset = _serializer.string(obj.feedback, buffer, bufferOffset);
    // Serialize message field [percentage_finished]
    bufferOffset = _serializer.float64(obj.percentage_finished, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type mobile_robot_pick_and_placeFeedback
    let len;
    let data = new mobile_robot_pick_and_placeFeedback(null);
    // Deserialize message field [feedback]
    data.feedback = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [percentage_finished]
    data.percentage_finished = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.feedback.length;
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rt_mission_msgs/mobile_robot_pick_and_placeFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '504e74cc782f32ca4d00b0cb52a2dc8c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    string feedback
    float64 percentage_finished
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new mobile_robot_pick_and_placeFeedback(null);
    if (msg.feedback !== undefined) {
      resolved.feedback = msg.feedback;
    }
    else {
      resolved.feedback = ''
    }

    if (msg.percentage_finished !== undefined) {
      resolved.percentage_finished = msg.percentage_finished;
    }
    else {
      resolved.percentage_finished = 0.0
    }

    return resolved;
    }
};

module.exports = mobile_robot_pick_and_placeFeedback;
