# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from holonomic_controller/DockingGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class DockingGoal(genpy.Message):
  _md5sum = "4a01939c8197b95cd380fc2893fea6c5"
  _type = "holonomic_controller/DockingGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Goal
string goal_parent_frame
geometry_msgs/Point goal_position
geometry_msgs/Vector3 goal_euler_orientation
float64 goal_tolerance
float64 lin_vel_max

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['goal_parent_frame','goal_position','goal_euler_orientation','goal_tolerance','lin_vel_max']
  _slot_types = ['string','geometry_msgs/Point','geometry_msgs/Vector3','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       goal_parent_frame,goal_position,goal_euler_orientation,goal_tolerance,lin_vel_max

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DockingGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.goal_parent_frame is None:
        self.goal_parent_frame = ''
      if self.goal_position is None:
        self.goal_position = geometry_msgs.msg.Point()
      if self.goal_euler_orientation is None:
        self.goal_euler_orientation = geometry_msgs.msg.Vector3()
      if self.goal_tolerance is None:
        self.goal_tolerance = 0.
      if self.lin_vel_max is None:
        self.lin_vel_max = 0.
    else:
      self.goal_parent_frame = ''
      self.goal_position = geometry_msgs.msg.Point()
      self.goal_euler_orientation = geometry_msgs.msg.Vector3()
      self.goal_tolerance = 0.
      self.lin_vel_max = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.goal_parent_frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d().pack(_x.goal_position.x, _x.goal_position.y, _x.goal_position.z, _x.goal_euler_orientation.x, _x.goal_euler_orientation.y, _x.goal_euler_orientation.z, _x.goal_tolerance, _x.lin_vel_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.goal_position is None:
        self.goal_position = geometry_msgs.msg.Point()
      if self.goal_euler_orientation is None:
        self.goal_euler_orientation = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_parent_frame = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal_parent_frame = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.goal_position.x, _x.goal_position.y, _x.goal_position.z, _x.goal_euler_orientation.x, _x.goal_euler_orientation.y, _x.goal_euler_orientation.z, _x.goal_tolerance, _x.lin_vel_max,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.goal_parent_frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d().pack(_x.goal_position.x, _x.goal_position.y, _x.goal_position.z, _x.goal_euler_orientation.x, _x.goal_euler_orientation.y, _x.goal_euler_orientation.z, _x.goal_tolerance, _x.lin_vel_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.goal_position is None:
        self.goal_position = geometry_msgs.msg.Point()
      if self.goal_euler_orientation is None:
        self.goal_euler_orientation = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_parent_frame = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal_parent_frame = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.goal_position.x, _x.goal_position.y, _x.goal_position.z, _x.goal_euler_orientation.x, _x.goal_euler_orientation.y, _x.goal_euler_orientation.z, _x.goal_tolerance, _x.lin_vel_max,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
