# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from accerion_driver_msgs/RamRomStats.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import accerion_driver_msgs.msg

class RamRomStats(genpy.Message):
  _md5sum = "7806d72dc3ef14ad7527222b80c652ff"
  _type = "accerion_driver_msgs/RamRomStats"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 romAvailable
uint32 romTotal
uint32 sdAvailable
uint32 sdTotal
uint16 ramUsed
uint16 ramTotal
DirSizePart[] parts
================================================================================
MSG: accerion_driver_msgs/DirSizePart
uint16 type
uint32 sizeInMB
uint32 nameLength
string name"""
  __slots__ = ['romAvailable','romTotal','sdAvailable','sdTotal','ramUsed','ramTotal','parts']
  _slot_types = ['uint32','uint32','uint32','uint32','uint16','uint16','accerion_driver_msgs/DirSizePart[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       romAvailable,romTotal,sdAvailable,sdTotal,ramUsed,ramTotal,parts

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RamRomStats, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.romAvailable is None:
        self.romAvailable = 0
      if self.romTotal is None:
        self.romTotal = 0
      if self.sdAvailable is None:
        self.sdAvailable = 0
      if self.sdTotal is None:
        self.sdTotal = 0
      if self.ramUsed is None:
        self.ramUsed = 0
      if self.ramTotal is None:
        self.ramTotal = 0
      if self.parts is None:
        self.parts = []
    else:
      self.romAvailable = 0
      self.romTotal = 0
      self.sdAvailable = 0
      self.sdTotal = 0
      self.ramUsed = 0
      self.ramTotal = 0
      self.parts = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4I2H().pack(_x.romAvailable, _x.romTotal, _x.sdAvailable, _x.sdTotal, _x.ramUsed, _x.ramTotal))
      length = len(self.parts)
      buff.write(_struct_I.pack(length))
      for val1 in self.parts:
        _x = val1
        buff.write(_get_struct_H2I().pack(_x.type, _x.sizeInMB, _x.nameLength))
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.parts is None:
        self.parts = None
      end = 0
      _x = self
      start = end
      end += 20
      (_x.romAvailable, _x.romTotal, _x.sdAvailable, _x.sdTotal, _x.ramUsed, _x.ramTotal,) = _get_struct_4I2H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.parts = []
      for i in range(0, length):
        val1 = accerion_driver_msgs.msg.DirSizePart()
        _x = val1
        start = end
        end += 10
        (_x.type, _x.sizeInMB, _x.nameLength,) = _get_struct_H2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        self.parts.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4I2H().pack(_x.romAvailable, _x.romTotal, _x.sdAvailable, _x.sdTotal, _x.ramUsed, _x.ramTotal))
      length = len(self.parts)
      buff.write(_struct_I.pack(length))
      for val1 in self.parts:
        _x = val1
        buff.write(_get_struct_H2I().pack(_x.type, _x.sizeInMB, _x.nameLength))
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.parts is None:
        self.parts = None
      end = 0
      _x = self
      start = end
      end += 20
      (_x.romAvailable, _x.romTotal, _x.sdAvailable, _x.sdTotal, _x.ramUsed, _x.ramTotal,) = _get_struct_4I2H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.parts = []
      for i in range(0, length):
        val1 = accerion_driver_msgs.msg.DirSizePart()
        _x = val1
        start = end
        end += 10
        (_x.type, _x.sizeInMB, _x.nameLength,) = _get_struct_H2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        self.parts.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4I2H = None
def _get_struct_4I2H():
    global _struct_4I2H
    if _struct_4I2H is None:
        _struct_4I2H = struct.Struct("<4I2H")
    return _struct_4I2H
_struct_H2I = None
def _get_struct_H2I():
    global _struct_H2I
    if _struct_H2I is None:
        _struct_H2I = struct.Struct("<H2I")
    return _struct_H2I
