// Generated by gencpp from file rt_carriage_controller_msgs/rt_carriage_controllerAction.msg
// DO NOT EDIT!


#ifndef RT_CARRIAGE_CONTROLLER_MSGS_MESSAGE_RT_CARRIAGE_CONTROLLERACTION_H
#define RT_CARRIAGE_CONTROLLER_MSGS_MESSAGE_RT_CARRIAGE_CONTROLLERACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rt_carriage_controller_msgs/rt_carriage_controllerActionGoal.h>
#include <rt_carriage_controller_msgs/rt_carriage_controllerActionResult.h>
#include <rt_carriage_controller_msgs/rt_carriage_controllerActionFeedback.h>

namespace rt_carriage_controller_msgs
{
template <class ContainerAllocator>
struct rt_carriage_controllerAction_
{
  typedef rt_carriage_controllerAction_<ContainerAllocator> Type;

  rt_carriage_controllerAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  rt_carriage_controllerAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rt_carriage_controller_msgs::rt_carriage_controllerActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::rt_carriage_controller_msgs::rt_carriage_controllerActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::rt_carriage_controller_msgs::rt_carriage_controllerActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> const> ConstPtr;

}; // struct rt_carriage_controllerAction_

typedef ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<std::allocator<void> > rt_carriage_controllerAction;

typedef boost::shared_ptr< ::rt_carriage_controller_msgs::rt_carriage_controllerAction > rt_carriage_controllerActionPtr;
typedef boost::shared_ptr< ::rt_carriage_controller_msgs::rt_carriage_controllerAction const> rt_carriage_controllerActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator1> & lhs, const ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator1> & lhs, const ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rt_carriage_controller_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04908d3e3d51140f2cd5200882250ef4";
  }

  static const char* value(const ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04908d3e3d51140fULL;
  static const uint64_t static_value2 = 0x2cd5200882250ef4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt_carriage_controller_msgs/rt_carriage_controllerAction";
  }

  static const char* value(const ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"rt_carriage_controllerActionGoal action_goal\n"
"rt_carriage_controllerActionResult action_result\n"
"rt_carriage_controllerActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: rt_carriage_controller_msgs/rt_carriage_controllerActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"rt_carriage_controllerGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rt_carriage_controller_msgs/rt_carriage_controllerGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"int32 MOVE_UNDEFINED_REQUEST=0\n"
"int32 MOVE_ABSOLUTE      =1\n"
"int32 MOVE_RELATIVE      =2\n"
"int32 CALIBRATE_REACH    =3\n"
"int32 CALIBRATE_LIFT     =4\n"
"int32 CALIBRATE_TILT     =5\n"
"int32 CALIBRATE_SIDESHIFT =6\n"
"\n"
"int32 move_type_enum\n"
"\n"
"float64 position_Goal\n"
"float32 position_tolerance\n"
"int32 mission_type_enum\n"
"int32 MISSION_PICK = 1\n"
"int32 MISSION_PLACE = 2\n"
"int32 SENSOR_NO_SENSE                              =7\n"
"int32 SENSOR_REACH_PAYLOAD_SENSE_LINEAR_CHANGE     =8\n"
"int32 SENSOR_REACH_PAYLOAD_SENSE_NO_CHANGE         =9\n"
"int32 SENSOR_REACH_FORKTIP_SENSE_COLLISION_CHANGE  =10\n"
"int32 SENSOR_REACH_UNTIL_FORKTIP_SENSE_SENSE_VALUE =11\n"
"int32 SENSOR_LIFT_UNTIL_LASER_READING =12\n"
"int32 sensor_type_enum\n"
"\n"
"float64 forktip_distance\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rt_carriage_controller_msgs/rt_carriage_controllerActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"rt_carriage_controllerResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rt_carriage_controller_msgs/rt_carriage_controllerResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"bool success_Result\n"
"\n"
"int32 ERROR_EXCEEDED_TRAVEL=0\n"
"int32 ERROR_TIMEOUT=1\n"
"int32 ERROR_UNDEFINED_MOVE_TYPE=2\n"
"int32 ERROR_UNDEFINED_SENSOR_TYPE=3\n"
"int32 ERROR_STALL_DETECTED=4\n"
"int32 ERROR_DEADMAN_IS_OFF=5\n"
"\n"
"int32 error_enum\n"
"\n"
"float64 exceeded_distance\n"
"float64 allowable_distance\n"
"float64 final_position\n"
"\n"
"================================================================================\n"
"MSG: rt_carriage_controller_msgs/rt_carriage_controllerActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"rt_carriage_controllerFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: rt_carriage_controller_msgs/rt_carriage_controllerFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 percentage_finished\n"
"\n"
"\n"
;
  }

  static const char* value(const ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rt_carriage_controllerAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt_carriage_controller_msgs::rt_carriage_controllerAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::rt_carriage_controller_msgs::rt_carriage_controllerActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::rt_carriage_controller_msgs::rt_carriage_controllerActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::rt_carriage_controller_msgs::rt_carriage_controllerActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT_CARRIAGE_CONTROLLER_MSGS_MESSAGE_RT_CARRIAGE_CONTROLLERACTION_H
