(cl:in-package monitor_utils-msg)
(cl:export '(SEQUENCE-VAL
          SEQUENCE
          NAME-VAL
          NAME
          WATCH_RATE-VAL
          WATCH_RATE
          STARTUP_DURATION-VAL
          STARTUP_DURATION
          PID-VAL
          PID
          INSTANTIATION_TIME-VAL
          INSTANTIATION_TIME
          WATCHED_TOPICS-VAL
          WATCHED_TOPICS
          IS_ALIVE-VAL
          IS_ALIVE
          IS_HUNG-VAL
          IS_HUNG
          IS_PUBLISHING-VAL
          IS_PUBLISHING
          REBOOT_ON_HANG-VAL
          REBOOT_ON_HANG
          REBOOT_ON_DEATH-VAL
          REBOOT_ON_DEATH
          REBOOT_ON_PUBLISH_TIMEOUT-VAL
          REBOOT_ON_PUBLISH_TIMEOUT
          REBOOT_COUNT-VAL
          REBOOT_COUNT
          LAUNCH_SCRIPT-VAL
          LAUNCH_SCRIPT
))