// Auto-generated. Do not edit!

// (in-package accerion_driver_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RetrieveLogsGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.path = null;
      this.backup_logs = null;
    }
    else {
      if (initObj.hasOwnProperty('path')) {
        this.path = initObj.path
      }
      else {
        this.path = '';
      }
      if (initObj.hasOwnProperty('backup_logs')) {
        this.backup_logs = initObj.backup_logs
      }
      else {
        this.backup_logs = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RetrieveLogsGoal
    // Serialize message field [path]
    bufferOffset = _serializer.string(obj.path, buffer, bufferOffset);
    // Serialize message field [backup_logs]
    bufferOffset = _serializer.bool(obj.backup_logs, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RetrieveLogsGoal
    let len;
    let data = new RetrieveLogsGoal(null);
    // Deserialize message field [path]
    data.path = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [backup_logs]
    data.backup_logs = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.path.length;
    return length + 5;
  }

  static datatype() {
    // Returns string type for a message object
    return 'accerion_driver_msgs/RetrieveLogsGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd229c956cdfc5fe93f7272546acbcd70';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal
    string path                 # Path where the logs should be stored
    bool backup_logs             # boolean, set to true if backup logs are to be retrieved.
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RetrieveLogsGoal(null);
    if (msg.path !== undefined) {
      resolved.path = msg.path;
    }
    else {
      resolved.path = ''
    }

    if (msg.backup_logs !== undefined) {
      resolved.backup_logs = msg.backup_logs;
    }
    else {
      resolved.backup_logs = false
    }

    return resolved;
    }
};

module.exports = RetrieveLogsGoal;
