// Auto-generated. Do not edit!

// (in-package accerion_driver_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let SubsetMapActionGoal = require('./SubsetMapActionGoal.js');
let SubsetMapActionResult = require('./SubsetMapActionResult.js');
let SubsetMapActionFeedback = require('./SubsetMapActionFeedback.js');

//-----------------------------------------------------------

class SubsetMapAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new SubsetMapActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new SubsetMapActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new SubsetMapActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SubsetMapAction
    // Serialize message field [action_goal]
    bufferOffset = SubsetMapActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = SubsetMapActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = SubsetMapActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SubsetMapAction
    let len;
    let data = new SubsetMapAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = SubsetMapActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = SubsetMapActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = SubsetMapActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += SubsetMapActionGoal.getMessageSize(object.action_goal);
    length += SubsetMapActionResult.getMessageSize(object.action_result);
    length += SubsetMapActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'accerion_driver_msgs/SubsetMapAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '79a0a3a902cb7fe90e5cfb71079ec0c3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    SubsetMapActionGoal action_goal
    SubsetMapActionResult action_result
    SubsetMapActionFeedback action_feedback
    
    ================================================================================
    MSG: accerion_driver_msgs/SubsetMapActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    SubsetMapGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: accerion_driver_msgs/SubsetMapGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal
    string clusterIDs           # idxs of the clusters to be moved(e.g. 0-100,102)
    uint16 targetAreaID         # id of the targetArea, has to be unused/empty
    
    ================================================================================
    MSG: accerion_driver_msgs/SubsetMapActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    SubsetMapResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: accerion_driver_msgs/SubsetMapResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # result
    bool done                   # sets the action to a finite state
    bool success                # bool that holds whether the request was succesful
    string message              # message containing information about the result
    uint16[] failedIDs          # ID's of the clusters that could not be found and/or copied
    
    ================================================================================
    MSG: accerion_driver_msgs/SubsetMapActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    SubsetMapFeedback feedback
    
    ================================================================================
    MSG: accerion_driver_msgs/SubsetMapFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32 progress              # message that contains information about the current progress
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SubsetMapAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = SubsetMapActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new SubsetMapActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = SubsetMapActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new SubsetMapActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = SubsetMapActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new SubsetMapActionFeedback()
    }

    return resolved;
    }
};

module.exports = SubsetMapAction;
