; Auto-generated. Do not edit!


(cl:in-package accerion_driver_msgs-msg)


;//! \htmlinclude UpdateSensorGoal.msg.html

(cl:defclass <UpdateSensorGoal> (roslisp-msg-protocol:ros-message)
  ((path
    :reader path
    :initarg :path
    :type cl:string
    :initform ""))
)

(cl:defclass UpdateSensorGoal (<UpdateSensorGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <UpdateSensorGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'UpdateSensorGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name accerion_driver_msgs-msg:<UpdateSensorGoal> is deprecated: use accerion_driver_msgs-msg:UpdateSensorGoal instead.")))

(cl:ensure-generic-function 'path-val :lambda-list '(m))
(cl:defmethod path-val ((m <UpdateSensorGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader accerion_driver_msgs-msg:path-val is deprecated.  Use accerion_driver_msgs-msg:path instead.")
  (path m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <UpdateSensorGoal>) ostream)
  "Serializes a message object of type '<UpdateSensorGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'path))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'path))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <UpdateSensorGoal>) istream)
  "Deserializes a message object of type '<UpdateSensorGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'path) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'path) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<UpdateSensorGoal>)))
  "Returns string type for a message object of type '<UpdateSensorGoal>"
  "accerion_driver_msgs/UpdateSensorGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'UpdateSensorGoal)))
  "Returns string type for a message object of type 'UpdateSensorGoal"
  "accerion_driver_msgs/UpdateSensorGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<UpdateSensorGoal>)))
  "Returns md5sum for a message object of type '<UpdateSensorGoal>"
  "1d00cd540af97efeb6b1589112fab63e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'UpdateSensorGoal)))
  "Returns md5sum for a message object of type 'UpdateSensorGoal"
  "1d00cd540af97efeb6b1589112fab63e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<UpdateSensorGoal>)))
  "Returns full string definition for message of type '<UpdateSensorGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%string path                 # Path where the update file is~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'UpdateSensorGoal)))
  "Returns full string definition for message of type 'UpdateSensorGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%string path                 # Path where the update file is~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <UpdateSensorGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'path))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <UpdateSensorGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'UpdateSensorGoal
    (cl:cons ':path (path msg))
))
