(cl:defpackage rt_mission_msgs-msg
  (:use )
  (:export
   "<MOBILE_ROBOT_PICK_AND_PLACEACTION>"
   "MOBILE_ROBOT_PICK_AND_PLACEACTION"
   "<MOBILE_ROBOT_PICK_AND_PLACEACTIONFEEDBACK>"
   "MOBILE_ROBOT_PICK_AND_PLACEACTIONFEEDBACK"
   "<MOBILE_ROBOT_PICK_AND_PLACEACTIONGOAL>"
   "MOBILE_ROBOT_PICK_AND_PLACEACTIONGOAL"
   "<MOBILE_ROBOT_PICK_AND_PLACEACTIONRESULT>"
   "MOBILE_ROBOT_PICK_AND_PLACEACTIONRESULT"
   "<MOBILE_ROBOT_PICK_AND_PLACEFEEDBACK>"
   "MOBILE_ROBOT_PICK_AND_PLACEFEEDBACK"
   "<MOBILE_ROBOT_PICK_AND_PLACEGOAL>"
   "MOBILE_ROBOT_PICK_AND_PLACEGOAL"
   "<MOBILE_ROBOT_PICK_AND_PLACERESULT>"
   "MOBILE_ROBOT_PICK_AND_PLACERESULT"
   "<PALLET_LOCATION>"
   "PALLET_LOCATION"
   "<RT_MISSION>"
   "RT_MISSION"
   "<RT_MISSION_QUEUE>"
   "RT_MISSION_QUEUE"
   "<USER_INPUT_REQUEST>"
   "USER_INPUT_REQUEST"
  ))

