; Auto-generated. Do not edit!


(cl:in-package rt_mission_msgs-msg)


;//! \htmlinclude mobile_robot_pick_and_placeGoal.msg.html

(cl:defclass <mobile_robot_pick_and_placeGoal> (roslisp-msg-protocol:ros-message)
  ((mission
    :reader mission
    :initarg :mission
    :type rt_mission_msgs-msg:rt_mission
    :initform (cl:make-instance 'rt_mission_msgs-msg:rt_mission)))
)

(cl:defclass mobile_robot_pick_and_placeGoal (<mobile_robot_pick_and_placeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <mobile_robot_pick_and_placeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'mobile_robot_pick_and_placeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rt_mission_msgs-msg:<mobile_robot_pick_and_placeGoal> is deprecated: use rt_mission_msgs-msg:mobile_robot_pick_and_placeGoal instead.")))

(cl:ensure-generic-function 'mission-val :lambda-list '(m))
(cl:defmethod mission-val ((m <mobile_robot_pick_and_placeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rt_mission_msgs-msg:mission-val is deprecated.  Use rt_mission_msgs-msg:mission instead.")
  (mission m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <mobile_robot_pick_and_placeGoal>) ostream)
  "Serializes a message object of type '<mobile_robot_pick_and_placeGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'mission) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <mobile_robot_pick_and_placeGoal>) istream)
  "Deserializes a message object of type '<mobile_robot_pick_and_placeGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'mission) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<mobile_robot_pick_and_placeGoal>)))
  "Returns string type for a message object of type '<mobile_robot_pick_and_placeGoal>"
  "rt_mission_msgs/mobile_robot_pick_and_placeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'mobile_robot_pick_and_placeGoal)))
  "Returns string type for a message object of type 'mobile_robot_pick_and_placeGoal"
  "rt_mission_msgs/mobile_robot_pick_and_placeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<mobile_robot_pick_and_placeGoal>)))
  "Returns md5sum for a message object of type '<mobile_robot_pick_and_placeGoal>"
  "a843553ccf8a45331ceb3bdc80ff87ce")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'mobile_robot_pick_and_placeGoal)))
  "Returns md5sum for a message object of type 'mobile_robot_pick_and_placeGoal"
  "a843553ccf8a45331ceb3bdc80ff87ce")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<mobile_robot_pick_and_placeGoal>)))
  "Returns full string definition for message of type '<mobile_robot_pick_and_placeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%rt_mission_msgs/rt_mission mission~%~%================================================================================~%MSG: rt_mission_msgs/rt_mission~%int32 task_enum~%int32 TASK_PICK_AND_PLACE=0~%int32 TASK_PICK=1~%int32 TASK_PLACE=2~%int32 TASK_CHARGE_ROBOT=3~%string status~%string pick_location_name~%string place_location_name~%string pick_stage_name~%string place_stage_name~%geometry_msgs/Pose pick_location~%geometry_msgs/Pose pick_stage_location~%geometry_msgs/Pose place_location~%geometry_msgs/Pose place_stage_location~%string pallet_id~%float32 pick_slot_height~%float32 place_slot_height~%string pick_approach_direction~%string place_approach_direction~%string pick_edge_case_direction~%string place_edge_case_direction~%bool priority~%bool payload_dimension~%float32 mission_complete_time~%float32 mission_distance~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'mobile_robot_pick_and_placeGoal)))
  "Returns full string definition for message of type 'mobile_robot_pick_and_placeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%rt_mission_msgs/rt_mission mission~%~%================================================================================~%MSG: rt_mission_msgs/rt_mission~%int32 task_enum~%int32 TASK_PICK_AND_PLACE=0~%int32 TASK_PICK=1~%int32 TASK_PLACE=2~%int32 TASK_CHARGE_ROBOT=3~%string status~%string pick_location_name~%string place_location_name~%string pick_stage_name~%string place_stage_name~%geometry_msgs/Pose pick_location~%geometry_msgs/Pose pick_stage_location~%geometry_msgs/Pose place_location~%geometry_msgs/Pose place_stage_location~%string pallet_id~%float32 pick_slot_height~%float32 place_slot_height~%string pick_approach_direction~%string place_approach_direction~%string pick_edge_case_direction~%string place_edge_case_direction~%bool priority~%bool payload_dimension~%float32 mission_complete_time~%float32 mission_distance~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <mobile_robot_pick_and_placeGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'mission))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <mobile_robot_pick_and_placeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'mobile_robot_pick_and_placeGoal
    (cl:cons ':mission (mission msg))
))
