; Auto-generated. Do not edit!


(cl:in-package rt_carriage_controller_msgs-msg)


;//! \htmlinclude rt_carriage_controllerFeedback.msg.html

(cl:defclass <rt_carriage_controllerFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage_finished
    :reader percentage_finished
    :initarg :percentage_finished
    :type cl:float
    :initform 0.0))
)

(cl:defclass rt_carriage_controllerFeedback (<rt_carriage_controllerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <rt_carriage_controllerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'rt_carriage_controllerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rt_carriage_controller_msgs-msg:<rt_carriage_controllerFeedback> is deprecated: use rt_carriage_controller_msgs-msg:rt_carriage_controllerFeedback instead.")))

(cl:ensure-generic-function 'percentage_finished-val :lambda-list '(m))
(cl:defmethod percentage_finished-val ((m <rt_carriage_controllerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rt_carriage_controller_msgs-msg:percentage_finished-val is deprecated.  Use rt_carriage_controller_msgs-msg:percentage_finished instead.")
  (percentage_finished m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <rt_carriage_controllerFeedback>) ostream)
  "Serializes a message object of type '<rt_carriage_controllerFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'percentage_finished))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <rt_carriage_controllerFeedback>) istream)
  "Deserializes a message object of type '<rt_carriage_controllerFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentage_finished) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<rt_carriage_controllerFeedback>)))
  "Returns string type for a message object of type '<rt_carriage_controllerFeedback>"
  "rt_carriage_controller_msgs/rt_carriage_controllerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'rt_carriage_controllerFeedback)))
  "Returns string type for a message object of type 'rt_carriage_controllerFeedback"
  "rt_carriage_controller_msgs/rt_carriage_controllerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<rt_carriage_controllerFeedback>)))
  "Returns md5sum for a message object of type '<rt_carriage_controllerFeedback>"
  "9095a553dcd7ab17f485835d069ce951")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'rt_carriage_controllerFeedback)))
  "Returns md5sum for a message object of type 'rt_carriage_controllerFeedback"
  "9095a553dcd7ab17f485835d069ce951")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<rt_carriage_controllerFeedback>)))
  "Returns full string definition for message of type '<rt_carriage_controllerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage_finished~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'rt_carriage_controllerFeedback)))
  "Returns full string definition for message of type 'rt_carriage_controllerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage_finished~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <rt_carriage_controllerFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <rt_carriage_controllerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'rt_carriage_controllerFeedback
    (cl:cons ':percentage_finished (percentage_finished msg))
))
